export const monitorConfig = {
    ACTIONS: {
        USER: {
            LOGIN: 'USER_LOGIN',
            LOGOUT: 'USER_LOGOUT',
            ACCESS: 'USER_ACCESS'
        },
        REPORT: {
            SAVE_REPORT: 'REPORT_SAVE_REPORT',
            EXPORT_TO_PDF: 'REPORT_EXPORT_TO_PDF',
            EXPORT_TO_GOOGLE_SHEETS: 'REPORT_EXPORT_TO_GOOGLE_SHEETS',
            SHARE_REPORT: 'REPORT_SHARE_REPORT',
            VIEW_REPORT: 'VIEW_REPORT'
        },
        MY_REPORT_TEMPLATE: {
            CREATE_REPORT: 'MY_REPORT_TEMPLATE_CREATE_REPORT',
            APPLY_FILTER: 'MY_REPORT_TEMPLATE_APPLY_FILTER',
            SEARCH_REPORT: 'MY_REPORT_TEMPLATE_SEARCH_REPORT',
            EDIT_INLINE_REPORT: 'MY_REPORT_TEMPLATE_EDIT_INLINE_REPORT',
            DELETE_REPORT: 'MY_REPORT_TEMPLATE_DELETE_REPORT',
            VIEW_REPORT: 'VIEW_REPORT'
        },
        SHARED_WITH_ME: {
            APPLY_FILTER: 'SHARED_WITH_ME_APPLY_FILTER',
            SEARCH_REPORT: 'SHARED_WITH_ME_SEARCH_REPORT'
        },
        PUBLIC_ON_NETWORK: {
            APPLY_FILTER: 'PUBLIC_ON_NETWORK_APPLY_FILTER',
            SEARCH_REPORT: 'PUBLIC_ON_NETWORK_SEARCH_REPORT'
        },
        GALLERY: {
            USE_TEMPLATE: 'GALLERY_USE_TEMPLATE'
        },
        DATA_SOURCES: {
            CREATE_DATA_SOURCE: 'DATA_SOURCES_CREATE_DATA_SOURCE',
            SHARED_WITH_ME: {
                APPLY_FILTER: 'SHARED_WITH_ME_APPLY_FILTER',
                SEARCH_REPORT: 'SHARED_WITH_ME_SEARCH_REPORT'
            },
            PUBLIC_ON_NETWORK: {
                APPLY_FILTER: 'PUBLIC_ON_NETWORK_APPLY_FILTER',
                SEARCH_REPORT: 'PUBLIC_ON_NETWORK_SEARCH_REPORT'
            }
        },
        CHANGE_ROUTE: 'CHANGE_ROUTE'
    }
};

export const workflowActionIdLog = {
    DATAFLOW_NAME: 100021,
    DESTINATION_CHANNEL: 100020,
    GO_TO_OTHER_ACTION: 100019,
    IF_THEN: 100018,
    DELAY: 100017,
    PREPARE_DATA: 100016,
    SUPPRESSION_LIST: 100015,
    UN_ENROLLMENT: 100014,
    TIMING_SETTING: 100013
};
