export const appConfig = {
    API_HOST: API_HOST, // 'http://thanghn.antalyser.adxdev.vn/api/',
    API_LOGGING: typeof API_LOGGING !== 'undefined' ? API_LOGGING : '',
    API_LOGGING_ERROR: typeof API_LOGGING_ERROR !== 'undefined' ? API_LOGGING_ERROR : '',
    LANGUAGE: typeof LANGUAGE !== 'undefined' ? LANGUAGE : [19552, 28992, 80829].indexOf(+API_ID) >= 0 ? 'vi' : 'en',
    VERSION: typeof ST_VERSION !== 'undefined' ? ST_VERSION : '1478967892',
    MONITOR_PID: typeof MONITOR_PID !== 'undefined' ? MONITOR_PID : '1583495368756',
    SITE_URL: SITE_URL,
    LOGO_MAIN: typeof LOGO_MAIN !== 'undefined' ? LOGO_MAIN : null,
    LOGO_SUB: LOGO_SUB,
    ASSETS_URL: ASSETS_URL,
    API_ID: API_ID,
    U_OGS: U_OGS,
    AUTH_ADX_DOMAIN: AUTH_ADX_DOMAIN,
    ST_OGS: ST_OGS,
    ST_URL_UPLOAD: ST_URL_UPLOAD,
    APPLICATION_ENV: APPLICATION_ENV,
    SECRET_KEY: 'ANTS',
    DATE_FORMAT: 'dd/mm/yy',
    MOMENT_DATE_FORMAT: 'DD/MM/YYYY',
    MOMENT_DATETIME_FORMAT: 'DD/MM/YYYY HH:mm:ss',
    KEY_CODE_ARROW_UP: 38,
    KEY_CODE_ARROW_DOWN: 40,
    KEY_CODE_ESC: 27,
    KEY_CODE_ENTER: 13,
    KEY_CODE_SPACE: 32,
    KEY_CODE_BACKSPACE: 8,
    VERSION_STYLE: 1,
    LOCAL_STORAGE_PREFIX: 'antalyser'
};
